version: '3'
services:

  eureka:
    image: "demo/demo-eureka"
    ports:
      - "8762:8762"
    environment:
      - "spring_profiles_active=docker"


  config:
    image: "demo/demo-config"
    ports:
      - "59001:59001"
    environment:
      - "spring_profiles_active=docker"
    depends_on:
      - eureka

  zookeeper:
    image: "wurstmeister/zookeeper"
    ports:
      - "2181:2181"

  kafka1:
    image: "wurstmeister/kafka"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka1"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

#  stream:
#    image: "demo/demo-stream"
#    depends_on:
#      - kafka1
#    ports:
#      - "59301:59301"
      
      
      
networks:
  default:
    external:
      name: spring-cloud-network