version: '3'
services:

  eureka:
    image: "demo/demo-eureka"
    ports:
      - "8762:8762"
    environment:
      - "spring_profiles_active=docker"


  config:
    image: "demo/demo-config"
    ports:
      - "59001:59001"
    environment:
      - "spring_profiles_active=docker"
    depends_on:
      - eureka

#  rabbitmq:
#    image: "rabbitmq:management"
#    environment:
#      - "RABBITMQ_DEFAULT_USER=admin"
#      - "RABBITMQ_DEFAULT_PASS=admin"
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#      - "25672:25672"
#      - "1883:1883"

  zookeeper:
    image: "wurstmeister/zookeeper"
    ports:
      - "2181:2181"

  kafka1:
    image: "wurstmeister/kafka"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_ADVERTISED_HOST_NAME=kafka1"
      - "KAFKA_CREATE_TOPICS=demo-stream"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"

  demo-stream:
    image: "demo/demo-stream"
    depends_on:
      - config
      - kafka1
#      - rabbitmq
    ports:
      - "59701:59701"
    environment:
      - "spring_profiles_active=docker"
    restart: always

#
      
networks:
  default:
    external:
      name: spring-cloud-network